language: python
python:
#    - "3.4"
	- "2.7"
install: 
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"
script: 
    - "coverage run --source=krobot setup.py test"
after_success:
    coveralls