language: python
python:
    - "2.7"
install: 
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"
    - "pip install codecov"
script: 
    - "coverage run --source=krobot setup.py test"
after_success:
    - coveralls
    - codecov
